# Defines the options for building the project on linux with Travis-CI
# For more configuration options, see the wiki:
# https://github.com/craigcitro/r-travis/wiki/Porting-to-native-R-support-in-Travis

language: r
sudo: required
warnings_ar_errors: true

before_install:
  - wget http://owi.usgs.gov/R/r-buildtools/JAGS-3.4.0.tar.gz
  - tar xfvs JAGS-3.4.0.tar.gz
  - cd JAGS-3.4.0
  - sudo ./configure
  - sudo make
  - sudo make install
  - cd ..
  - sudo rm -f JAGS-3.4.0.tar.gz
  - sudo rm -rf JAGS-3.4.0

r_github_packages:
 - jimhester/covr
 - appling/unitted
 - aappling-usgs/LakeMetabolizer

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
