
language: r
sudo: required

r_github_packages:
 - jimhester/covr
 - appling/unitted
 - USGS-R/sbtools
 - USGS-R/geoknife

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
