
language: r
sudo: required

r_github_packages:
 - jimhester/covr
 - appling/unitted@v0.2.0
 - USGS-R/sbtools
 - USGS-R/geoknife
 - USGS-R/mda.streams
 - USGS-R/powstreams

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
