
language: r
sudo: required

r_github_packages:
 - jimhester/covr
 - appling/unitted

after_success:
  - Rscript -e 'covr::coveralls()'

notifications:
  email:
    on_success: change
    on_failure: change
