init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/jread-usgs/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  - ps: Bootstrap
  - ps: pwd
  - cmd: dir
  - ps: (new-object net.webclient).DownloadFile('http://downloads.sourceforge.net/project/mcmc-jags/JAGS/3.x/Windows/JAGS-3.4.0.exe?r=&ts=1440685498', '.\JAGS-3.4.0.exe')
  - cmd: dir
  - cmd: .\JAGS-3.4.0.exe /S
  - cmd: dir

build_script:
  - travis-tool.sh install_github appling/unitted
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
